services:
  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    image: original-app:latest
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - node

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_db
      MYSQL_USER: node_user
      MYSQL_PASSWORD: node_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=node_user
      - PMA_PASSWORD=node_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"
